environment:
  nodejs_version: "12.2.0"

install:
  - ps: Write-Host $env:nodejs_version
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run build
  - npm test

build: off
